"""Render plans as dbt `schema.yml`, plus a human-readable evidence report."""

from __future__ import annotations

from typing import Mapping, Sequence

import yaml

from .inference import REFUSAL_KINDS, ModelPlan, refusal_summary


class _Dumper(yaml.SafeDumper):
    """Block style everywhere, and indented sequences — matches dbt convention."""

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def _column_block(plan: ModelPlan, column: str, test_key: str,
                  nest_arguments: bool = True, include_refused: bool = False) -> dict | None:
    f = plan.dataset.field_by_path(column)
    tests = [t.to_yaml_obj(nest_arguments=nest_arguments)
             for t in plan.tests if t.column == column]
    refused = [
        r.would_have for r in plan.refusals
        if include_refused and r.column == column and r.kind == "contradicted"
    ] if include_refused else []
    if not tests and not refused and not (f and f.is_pii):
        return None

    block: dict = {"name": column}
    if f is not None:
        if f.description:
            block["description"] = f.description
        if f.native_type:
            block["data_type"] = f.native_type.lower()
        if f.is_pii:
            block["meta"] = {"contains_pii": True}
    if tests or refused:
        block[test_key] = tests + refused
    return block


def to_schema_yaml(plans: Sequence[ModelPlan], *, test_key: str = "data_tests",
                   nest_arguments: bool = True, include_refused: bool = False) -> str:
    """Build a dbt v2 schema file covering every planned model.

    With `include_refused`, the `not_null` tests that were retracted because the
    documentation contradicts the schema are added back. They are expected to
    fail: that failure is the evidence the retraction was correct.
    """
    models = []
    for plan in plans:
        ds = plan.dataset
        columns = []
        for f in ds.fields:
            block = _column_block(plan, f.path, test_key, nest_arguments, include_refused)
            if block:
                columns.append(block)
        if not columns:
            continue

        model: dict = {"name": ds.table}
        if ds.description:
            model["description"] = ds.description
        model["meta"] = {"datahub_urn": ds.urn}
        model["columns"] = columns
        models.append(model)

    counts = refusal_summary(plans)
    refused = sum(counts.values())
    if include_refused:
        header = (
            "# Generated by dbt-testgen — PROOF MODE.\n"
            f"# The {counts.get('contradicted', 0)} `not_null` tests that were retracted because\n"
            "# the catalog's documentation contradicts its schema have been added back.\n"
            "# They are expected to FAIL. That failure is the point: it shows the\n"
            "# retraction was correct and the schema flag was not.\n"
            "# Regenerate with:  dbt-testgen validate --with-refused\n\n"
        )
    else:
        header = (
            "# Generated by dbt-testgen from DataHub metadata.\n"
            "# Every test below cites a sentence a human wrote in a DataHub Document.\n"
            f"# {refused} further tests were declined for lack of such evidence and are\n"
            "# listed, with reasons, in EVIDENCE.md. Read that file before adding them\n"
            "# back by hand.\n"
            "# Regenerate with:  dbt-testgen generate\n\n"
        )
    doc = {"version": 2, "models": models}
    return header + yaml.dump(
        doc, Dumper=_Dumper, sort_keys=False, default_flow_style=False, allow_unicode=True
    )


def to_documentation_gaps(plans: Sequence[ModelPlan]) -> str:
    """The refusal report read the other way round: what to write down next.

    Every refusal is a test that could exist if somebody documented one column.
    Sorted by how many tests each model would gain, this is a work queue for
    whoever owns the catalog.
    """
    ranked = sorted(
        ((p, [r for r in p.refusals if r.kind != "nullability-flag"]) for p in plans),
        key=lambda pr: -len(pr[1]),
    )
    lines = [
        "Generated by `dbt-testgen`. Every line below is a dbt test that could exist "
        "if one column were documented.",
        "",
        "This tool builds tests from what people write in DataHub documents — declared "
        "keys, declared foreign keys, declared value sets, and which columns are "
        "legitimately empty. Where nothing is written down it emits nothing. So this "
        "list is the inverse of the test suite: the documentation that would pay for "
        "itself first.",
        "",
    ]
    for plan, refusals in ranked:
        if not refusals:
            continue
        lines.append(f"## {plan.dataset.table}")
        lines.append("")
        for r in refusals:
            lines.append(f"- `{r.column}` — no `{r.would_have}` test: {r.because}")
        lines.append("")

    flagged = sum(
        1 for p in plans for r in p.refusals if r.kind == "nullability-flag"
    )
    if flagged:
        lines += [
            "## Not listed above",
            "",
            f"A further {flagged} `not_null` tests were declined because the only "
            "evidence for them was the schema's nullability flag, which is a constant "
            "per platform in this catalog and so carries no information. Documenting "
            "which of these columns can actually be empty would turn each one into a "
            "real test.",
            "",
        ]
    return "\n".join(lines)


def to_evidence_report(
    plans: Sequence[ModelPlan],
    cross: Sequence = (),
    census: Mapping[str, Mapping[str, int]] | None = None,
    docs_read: int = 0,
) -> str:
    """Markdown explaining why each test exists — and why the others don't."""
    total_tests = sum(len(p.tests) for p in plans)
    refusals = refusal_summary(plans)
    total_refused = sum(refusals.values())
    modelled = [p for p in plans if p.tests]
    avg = round(sum(p.coverage for p in modelled) / len(modelled), 1) if modelled else 0.0

    lines = [
        "# Generated test evidence",
        "",
        f"**{total_tests} tests emitted. {total_refused} tests refused.**",
        "",
        f"Across {len(modelled)} models, mean column coverage {avg}%. Every emitted test cites "
        f"a sentence written by a human in one of the {docs_read} documents this DataHub "
        "deployment holds. Every refused test names the evidence that was missing.",
        "",
        "The second number is the one worth reading. A generated test that cannot be justified "
        "fails on correct data, and the reflex is to delete it — along with the tests that "
        "mattered.",
        "",
    ]

    if refusals:
        lines += ["## What was refused, and why", "",
                  "| Count | Refusal |", "| --- | --- |"]
        for kind, count in sorted(refusals.items(), key=lambda kv: -kv[1]):
            lines.append(f"| {count} | {REFUSAL_KINDS.get(kind, kind)} |")
        lines.append("")

    if census:
        lines += ["## Nullability census", "",
                  "The measurement behind the `not_null` policy, taken from the catalog itself.",
                  "", "| Platform | NOT NULL | nullable | varies? |", "| --- | --- | --- | --- |"]
        for platform, counts in sorted(census.items()):
            nn, nul = counts.get("not_null", 0), counts.get("nullable", 0)
            varies = "**yes**" if nn and nul else "no — constant"
            lines.append(f"| {platform} | {nn} | {nul} | {varies} |")
        lines.append("")

    if cross:
        lines += ["## Catalog-wide findings", "",
                  "These require comparing every model against every other, which is what a",
                  "metadata catalog makes possible and a single dbt project does not.", ""]
        for f in cross:
            marker = "**warn**" if f.severity == "warn" else "info"
            lines.append(f"- {marker} — {f.message}")
        lines.append("")

    for plan in sorted(plans, key=lambda p: (-len(p.tests), p.dataset.table)):
        if not (plan.tests or plan.findings or plan.refusals):
            continue
        lines.append(f"## `{plan.dataset.table}`")
        lines.append("")
        if plan.tests:
            lines.append(f"Coverage: {plan.coverage}% of columns "
                         f"({len(plan.tested_columns)}/{len(plan.dataset.fields)}).")
            lines.append("")
            lines.append("| Column | Test | Evidence |")
            lines.append("| --- | --- | --- |")
            for t in plan.tests:
                lines.append(f"| `{t.column}` | `{t.name}` | {t.because} |")
            lines.append("")
        if plan.refusals:
            lines.append("<details><summary>Refused here</summary>")
            lines.append("")
            lines.append("| Column | Not emitted | Why |")
            lines.append("| --- | --- | --- |")
            for r in plan.refusals:
                lines.append(f"| `{r.column}` | `{r.would_have}` | {r.because} |")
            lines.append("")
            lines.append("</details>")
            lines.append("")
        for f in plan.findings:
            marker = "**warn**" if f.severity == "warn" else "info"
            lines.append(f"- {marker} — {f.message}")
        if plan.findings:
            lines.append("")

    return "\n".join(lines)
