"""Render plans as dbt `schema.yml`, plus a human-readable evidence report."""

from __future__ import annotations

from typing import Sequence

import yaml

from .inference import ModelPlan


class _Dumper(yaml.SafeDumper):
    """Block style everywhere, and indented sequences — matches dbt convention."""

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def _column_block(plan: ModelPlan, column: str, test_key: str,
                  nest_arguments: bool = True) -> dict | None:
    f = plan.dataset.field_by_path(column)
    tests = [t for t in plan.tests if t.column == column]
    if not tests and not (f and f.is_pii):
        return None

    block: dict = {"name": column}
    if f is not None:
        if f.description:
            block["description"] = f.description
        if f.native_type:
            block["data_type"] = f.native_type.lower()
        if f.is_pii:
            block["meta"] = {"contains_pii": True}
    if tests:
        block[test_key] = [t.to_yaml_obj(nest_arguments=nest_arguments) for t in tests]
    return block


def to_schema_yaml(plans: Sequence[ModelPlan], *, test_key: str = "data_tests",
                   nest_arguments: bool = True) -> str:
    """Build a dbt v2 schema file covering every planned model."""
    models = []
    for plan in plans:
        ds = plan.dataset
        columns = []
        for f in ds.fields:
            block = _column_block(plan, f.path, test_key, nest_arguments)
            if block:
                columns.append(block)
        if not columns:
            continue

        model: dict = {"name": ds.table}
        if ds.description:
            model["description"] = ds.description
        meta: dict = {"datahub_urn": ds.urn}
        if ds.owners:
            meta["owners"] = list(ds.owners)
        model["meta"] = meta
        model["columns"] = columns
        models.append(model)

    doc = {"version": 2, "models": models}
    header = (
        "# Generated by dbt-testgen from DataHub metadata.\n"
        "# Every test below is derived from metadata DataHub holds — column\n"
        "# nullability, primary keys, real lineage edges and documented enums.\n"
        "# Nothing here is inferred from column names alone.\n"
        "# Regenerate with:  dbt-testgen generate\n\n"
    )
    return header + yaml.dump(
        doc, Dumper=_Dumper, sort_keys=False, default_flow_style=False, allow_unicode=True
    )


def to_evidence_report(plans: Sequence[ModelPlan], cross: Sequence = ()) -> str:
    """Markdown explaining why each test exists — the auditable half."""
    total_tests = sum(len(p.tests) for p in plans)
    modelled = [p for p in plans if p.tests]
    avg = round(sum(p.coverage for p in modelled) / len(modelled), 1) if modelled else 0.0

    lines = [
        "# Generated test evidence",
        "",
        f"**{total_tests} tests** across **{len(modelled)} models** — "
        f"mean column coverage **{avg}%**.",
        "",
        "Each test cites the DataHub metadata that justified it. Where the catalog "
        "was ambiguous, no test was emitted and the ambiguity is recorded as a finding.",
        "",
    ]

    if cross:
        lines += ["## Catalog-wide findings", "",
                  "These require comparing every model against every other, which is what a",
                  "metadata catalog makes possible and a single dbt project does not.", ""]
        for f in cross:
            marker = "**warn**" if f.severity == "warn" else "info"
            lines.append(f"- {marker} — {f.message}")
        lines.append("")

    for plan in sorted(plans, key=lambda p: -len(p.tests)):
        if not plan.tests and not plan.findings:
            continue
        lines.append(f"## `{plan.dataset.table}`")
        lines.append("")
        if plan.tests:
            lines.append(f"Coverage: {plan.coverage}% of columns "
                         f"({len(plan.tested_columns)}/{len(plan.dataset.fields)}).")
            lines.append("")
            lines.append("| Column | Test | Evidence |")
            lines.append("| --- | --- | --- |")
            for t in plan.tests:
                lines.append(f"| `{t.column}` | `{t.name}` | {t.because} |")
            lines.append("")
        for f in plan.findings:
            marker = "**warn**" if f.severity == "warn" else "info"
            lines.append(f"- {marker} — {f.message}")
        if plan.findings:
            lines.append("")

    return "\n".join(lines)
